package com.whyun.message.key;

public interface KeyMap {
	public static final int KeyLButton = 1;//鼠标左键
	public static final int KeyRButton = 2;//鼠标右键
	public static final int KeyCancel = 3;//CANCEL
	public static final int KeyMButton = 4;//鼠标中键
	public static final int KeyBack = 8;//BACKSPACE
	public static final int KeyTab = 9;//TAB
	public static final int KeyClear = 12;//CLEAR
	public static final int KeyReturn = 13;//ENTER
	public static final int KeyShift = 16;//SHIFT
	public static final int KeyControl = 17;//CTRL
	public static final int KeyMenu = 18;//菜单键
	public static final int KeyPause = 19;//PAUSE
	public static final int KeyCapital = 20;// CAPS LOCK
	public static final int KeyEscape = 27;//ESC
	public static final int KeySpace = 32;//SPACEBAR
	public static final int KeyPageUp = 33;//PAGEUP
	public static final int KeyPageDown = 34;//PAGEDOWN
	public static final int KeyEnd = 35;//END
	public static final int KeyHome = 36;//HOME
	public static final int KeyLeft = 37; // LEFT ARROW
	public static final int KeyUp = 38; //UP ARROW
	public static final int KeyRight = 39 ;//RIGHT ARROW
	public static final int KeyDown = 40; //DOWN ARROW
	public static final int KeySelect = 41;//SELECT
	public static final int KeyPrint = 42;// PRINT SCREEN
	public static final int KeyExecute = 43;//EXECUTE
	public static final int KeySnapshot= 44 ;// SNAP SHOT
	public static final int KeyInser = 45;//INS
	public static final int KeyDelete = 46;//DEL
	public static final int KeyHelp = 47;//HELP
	public static final int KeyNumlock = 144; // NUMLOCK
	public static final int KeyA = 65;//A
	public static final int KeyB = 66;//B
	public static final int KeyC = 67;//C
	public static final int KeyD = 68;//D
	public static final int KeyE = 69;//E
	public static final int KeyF = 70;//F
	public static final int KeyG = 71;//G
	public static final int KeyH = 72;//H
	public static final int KeyI = 73;//I
	public static final int KeyJ = 74;//J
	public static final int KeyK = 75;//K
	public static final int KeyL = 76;//L
	public static final int KeyM = 77;//M
	public static final int KeyN = 78;//N
	public static final int KeyO = 79;//O
	public static final int KeyP = 80;//P
	public static final int KeyQ = 81;//Q
	public static final int KeyR = 82;//R
	public static final int KeyS = 83;//S
	public static final int KeyT = 84;//T
	public static final int KeyU = 85;//U
	public static final int KeyV = 86;//V
	public static final int KeyW = 87;//W
	public static final int KeyX = 88;//X
	public static final int KeyY = 89;//Y
	public static final int KeyZ = 90;//Z
	public static final int Key0 = 48;//0
	public static final int Key1 = 49;//1
	public static final int Key2 = 50;//2
	public static final int Key3 = 51;//3
	public static final int Key4 = 52;//4
	public static final int Key5 = 53;//5
	public static final int Key6 = 54;//6
	public static final int Key7 = 55;//7
	public static final int Key8 = 56;//8
	public static final int Key9 = 57;//9
	public static final int KeyNumpad0 = 96;//0
	public static final int KeyNumpad1 = 97;//1
	public static final int KeyNumpad2 = 98;//2
	public static final int KeyNumpad3 = 99;//3
	public static final int KeyNumpad4 = 100;//4
	public static final int KeyNumpad5 = 101;//5
	public static final int KeyNumpad6 = 102;//6
	public static final int KeyNumpad7 = 103;//7
	public static final int KeyNumpad8 = 104;//8
	public static final int KeyNumpad9 = 105;//9
	public static final int KeyMultiply = 106;//乘号(*)
	public static final int KeyAdd = 107;//加号(+)
	public static final int KeySeparator = 108;//ENTER（在数字小键盘上）
	public static final int KeySubtract = 109;//减号(-)
	public static final int KeyDecimal = 110;//小数点(.)
	public static final int KeyDivide = 111;//除号(/)
	public static final int KeyF1 = 112;//F1
	public static final int KeyF2 = 113;//F2
	public static final int KeyF3 = 114;//F3
	public static final int KeyF4 = 115;//F4
	public static final int KeyF5 = 116;//F5
	public static final int KeyF6 = 117;//F6
	public static final int KeyF7 = 118;//F7
	public static final int KeyF8 = 119;//F8
	public static final int KeyF9 = 120;//F9
	public static final int KeyF10 = 121;//F10
	public static final int KeyF11 = 122;//F11
	public static final int KeyF12 = 123;//F12
	public static final int KeyF13 = 124;//F13
	public static final int KeyF14 = 125;//F14
	public static final int KeyF15 = 126;//F15
	public static final int KeyF16 = 127;//F16

}
